language: python
python:
  - 3.7
install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
  - pip install pytest-cov
script: pytest --cov=bioinformatics_stronghold bioinformatics_stronghold/*.py bioinformatics_stronghold/Bio --cov-report=xml 
after_success:
  - codecov # submit coverage